import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated;
create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
create table public.clientes(id uuid primary key,nome text,telefone text,email text,pontos int default 0,ativo boolean default true,atualizado_em timestamptz);
create table public.pedidos_fidelidade(cliente_id uuid);create table public.movimentacoes_pontos(cliente_id uuid);
create table public.configuracao_fidelidade(ativo boolean);create table public.resgates_checkout(order_id text);
create function public.criar_perfil_cliente() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.clientes(id,nome,telefone,email) values(new.id,coalesce(new.raw_user_meta_data->>'nome','Cliente'),new.raw_user_meta_data->>'telefone',new.email) on conflict(id) do nothing;return new;end; $$;
create function public.atualizar_data_modificacao() returns trigger language plpgsql as $$ begin new.atualizado_em=now();return new;end; $$;
create trigger criar_cliente_apos_cadastro after insert on auth.users for each row execute function public.criar_perfil_cliente();
create trigger atualizar_cliente_em before update on public.clientes for each row execute function public.atualizar_data_modificacao();
grant all on all tables in schema public to anon,authenticated,service_role;
alter table clientes enable row level security;
create policy own_read on clientes for select to authenticated using ((select auth.uid())=id);
create policy own_update on clientes for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
`);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260921014030_harden_public_permissions.sql',import.meta.url),'utf8'));
const alice='11111111-1111-4111-8111-111111111111',bob='22222222-2222-4222-8222-222222222222';
await db.query("insert into auth.users values($1,'alice@test.invalid','{}'),($2,'bob@test.invalid','{}')",[alice,bob]);
assert.equal((await db.query('select count(*)::int n from clientes')).rows[0].n,2);
await db.exec(`set role authenticated;set request.jwt.claim.sub='${alice}';`);
assert.equal((await db.query('select id from clientes')).rows.length,1);
await db.query("update clientes set nome='Alice',telefone='123' where id=$1",[alice]);
assert.ok((await db.query('select atualizado_em from clientes')).rows[0].atualizado_em);
await db.query("update clientes set nome='Wrong' where id=$1",[bob]);
for(const sql of ['update clientes set pontos=999','update clientes set ativo=false',"update clientes set email='wrong@test.invalid'",'truncate clientes','delete from clientes','select * from resgates_checkout','select criar_perfil_cliente()'])await assert.rejects(()=>db.exec(sql),/permission denied/);
await db.exec('reset role;set role anon');
await db.query('select * from configuracao_fidelidade');
await assert.rejects(()=>db.query('select * from clientes'),/permission denied/);
await db.exec('reset role;set role service_role');
await db.query('update clientes set pontos=50 where id=$1',[alice]);
assert.equal((await db.query('select nome from clientes where id=$1',[bob])).rows[0].nome,'Cliente');
assert.equal((await db.query('select pontos from clientes where id=$1',[alice])).rows[0].pontos,50);
console.log('PASS database permissions: signup trigger, profile update trigger, own rows, protected balance/status/email, no truncate/delete/private reads, server access preserved');
await db.close();
