const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url).pathname;const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create table clientes(id uuid primary key,pontos integer not null check(pontos>=0),ativo boolean default true);
create table movimentacoes_pontos(id serial primary key,cliente_id uuid,tipo text,pontos integer,descricao text,criado_em timestamptz);
grant select,update on clientes to service_role;grant insert on movimentacoes_pontos to service_role;grant usage on sequence movimentacoes_pontos_id_seq to service_role;`);
await db.exec(fs.readFileSync(root+'SUPABASE-V43-RESGATE-PONTOS.sql','utf8'));
await db.exec(fs.readFileSync(root+'SUPABASE-RESGATE-CARRINHO.sql','utf8'));
const uid='11111111-1111-4111-8111-111111111111';await db.query('insert into clientes(id,pontos) values($1,236)',[uid]);
const rpc=async(action,values)=>(await db.query('select checkout_resgate_v1($1,$2::jsonb) r',[action,JSON.stringify({customer_id:uid,order_id:'one',...values})])).rows[0].r;
await db.exec('set role service_role');
assert.equal((await rpc('open',{points:200,fingerprint:'a'})).created,true);
assert.equal((await rpc('open',{points:200,fingerprint:'a'})).created,false);
await assert.rejects(()=>rpc('open',{points:100,fingerprint:'b',order_id:'two'}),/PONTOS_INSUFICIENTES/);
await assert.rejects(()=>rpc('open',{points:100,fingerprint:'x'}),/CONFLITO/);
assert.equal((await db.query('select pontos from clientes')).rows[0].pontos,236);
await rpc('save',{order:{order_id:'one',payment_status:'pending'}});
await rpc('save',{order:{order_id:'one',payment_status:'approved'}});
await rpc('save',{order:{order_id:'one',payment_status:'approved'}});
assert.equal((await db.query('select pontos from clientes')).rows[0].pontos,36);
await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from movimentacoes_pontos')).rows[0].n,1);
await rpc('open',{points:30,fingerprint:'b',order_id:'two'});
await rpc('save',{order_id:'two',order:{order_id:'two',payment_status:'rejected'}});
await rpc('open',{points:30,fingerprint:'c',order_id:'three'});
await assert.rejects(()=>rpc('save',{order_id:'two',order:{order_id:'two',payment_status:'approved'}}),/RESERVA_LIBERADA/);
await db.exec('set role authenticated');await assert.rejects(()=>rpc('open',{points:1,fingerprint:'d',order_id:'four'}),/permission denied/);
console.log('SQL verified: reservations, insufficient available points, idempotency, debit once, release and role restrictions.');await db.close();
